#server:
#  port: 18082
#spring:
#  application:
#    name: workFlow
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/jacksonProject?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: root
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka
#  instance:
#    prefer-ip-address: true
#feign:
#  hystrix:
#    enabled: true
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.changgou.goods.vo