server:
  port: 10080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: jackson-provider-route
          uri: lb://jackson-provider
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1

        - id: jackson-customer-route
          uri: lb://jackson-customer
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka